# ===== 1) Build =====
FROM node:20-alpine AS build
WORKDIR /app
# Copia manifestos primeiro para aproveitar cache
COPY package*.json ./
RUN npm ci
# Copia restante do projeto
COPY . .
# Gera Prisma Client e compila Nest
RUN npm run prisma:generate || npx prisma generate
RUN npm run build


# ===== 2) Runtime =====
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production \
PORT=3000
# Apenas deps de runtime
COPY --from=build /app/package*.json ./
RUN npm ci --omit=dev
# Copia artefatos e prisma
COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma
# Se usar Swagger estático ou outras pastas, copie também
# EXPOSE 3000 # informativo
# Start: aplica migrations e sobe a API
CMD sh -c "node -v && npm run prisma:migrate && node dist/main.js"